var gameEvents = {
    CHAT: 'onChat',
    BROADCAST: 'onBroadcast',
    JOIN: 'onJoin',
    READY: 'onReady',
    LEAVE: 'onLeave',
    START: 'onStart',
    TALK_COUNTDOWN: 'onTalkCountdown',
    TALK_COUNTDOWN_TIMEOUT: 'onTalkCountdownTimeout',
    TALK: 'onTalk',
    AFTER_TALK: 'onAfterTalk',
    FAN_COUNTDOWN: 'onFanCountdown',
    FAN_COUNTDOWN_TIMEOUT: 'onFanCountdownTimeout',
    FAN: 'onFan',
    TRUSTEESHIP: 'onTrusteeship',
    CANCEL_TRUSTEESHIP: 'onCancelTrusteeship',
    OVER: 'onOver',
    GOLD_CHANGE: 'onGoldChange',
    FAN_WHEN_IS_RED: 'onFanWhenIsRed',
    FAN_FINISHED: 'onFanFinished',
    BACK_TO_GAME: 'onBackToGame',
    UI_COMMAND: 'onUICommand'
}